# Generated by Django 5.2.7 on 2026-03-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default='Main Field', max_length=100)),
                ('ph', models.FloatField(help_text='pH level (0-14)')),
                ('moisture', models.FloatField(help_text='Moisture percentage (0-100)')),
                ('nitrogen', models.FloatField(help_text='Nitrogen mg/kg')),
                ('phosphorus', models.FloatField(help_text='Phosphorus mg/kg')),
                ('potassium', models.FloatField(help_text='Potassium mg/kg')),
                ('temperature', models.FloatField(default=25.0, help_text='Soil temperature °C')),
                ('organic_matter', models.FloatField(default=2.5, help_text='Organic matter %')),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('critical', 'Critical')], editable=False, max_length=20)),
                ('health_score', models.IntegerField(default=0, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'soil_reports',
                'ordering': ['-tested_at'],
            },
        ),
    ]
