# Generated by Django 5.2.7 on 2026-03-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food_processing', 'Food Processing'), ('logistics', 'Logistics Partner'), ('corporate_buyer', 'Corporate Buyer'), ('export', 'Export Company'), ('retail', 'Retail Chain')], max_length=30)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('crops_interested', models.TextField(help_text='Comma-separated crop names')),
                ('monthly_requirement_tonnes', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('quantity_tonnes', models.FloatField()),
                ('price_per_tonne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_by', models.DateField()),
                ('quality_requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='companies.company')),
            ],
            options={
                'db_table': 'purchase_interests',
                'ordering': ['-created_at'],
            },
        ),
    ]
